logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: INFO

---

spring:
  config:
    activate:
      on-profile: default, local

management:
  endpoint:
    health:
      show-details: always

repositories:
  root:
    label: root
    datasource-class-name: org.h2.jdbcx.JdbcDataSource
    jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
  routes:
    -
      label: mysql
      datasource-class-name: com.mysql.cj.jdbc.MysqlXADataSource
      jdbc-url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC&pinGlobalTxToPhysicalConnection=true
      username: root
      password: 1234
    -
      label: mysql2
      datasource-class-name: com.mysql.cj.jdbc.MysqlXADataSource
      jdbc-url: jdbc:mysql://localhost:3306/test2?characterEncoding=UTF-8&serverTimezone=UTC&pinGlobalTxToPhysicalConnection=true
      username: root
      password: 1234
    -
      label: mysql_slave
      datasource-class-name: com.mysql.cj.jdbc.MysqlXADataSource
      jdbc-url: jdbc:mysql://localhost:3306/test2?characterEncoding=UTF-8&serverTimezone=UTC&pinGlobalTxToPhysicalConnection=true
      username: root
      password: 1234

---

spring:
  config:
    activate:
      on-profile: prod
